name: grant-actions
description: 'TODO'
inputs:
    step: # id of input
        description: 'grant workflow step issue2project, issue2pr, or pr2project'
        required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
