name: grant-actions
description: 'TODO'
inputs:
    myToken:
        description: 'github secrets token for octokit authentication'
        required: true
    step: # id of input
        description: 'grant workflow step issue2project, issue2pr, or pr2project'
        required: true
    projectURL:
        description: 'URL of grant applications repo'
        required: false
    columnName:
        description: 'Project column to move card to'
        required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
