name: grant-actions
description: 'TODO'
inputs:
    myToken:
        description: 'Github secrets token for octokit authentication'
        required: true
    step:
        description: 'Grant workflow step: card-for-request or request-to-review'
        required: true
    projectURL:
        description: 'URL of grant applications project'
        required: true
    requestColumn:
        description: 'Project column for new requests'
        required: true
    reviewColumn:
        description: 'Project column for requests to review'
        required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
