# Cribbing from https://github.com/takanabe/github-actions-automate-projects
name: "grant-application-workflow-actions"
on:
    issues:
        types: [opened, labeled]
    pull_request:
        types: [opened]
    
jobs:
    grant-actions:
        runs-on: ubuntu-latest
        steps:
 #       - name: add-project-card-for-issue-to-applications-column
 #         uses: ./
 #         if: github.event_name == 'issues' && github.event.action == 'opened'
 #         with:
 #           myToken: ${{ secrets.GITHUB_TOKEN }}
 #           step: 'issue2project'
 #           projectURL: 'https://github.com/nostarch-foundation/grant-actions/projects/1'
 #           columnName: 'Applications'
        - name: convert-issue-to-pr
          uses: ./
          if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label == 'Review'
          with:
            myToken: ${{ secrets.GITHUB_TOKEN }}
            step: 'issue2pr'
#        - name: move-card-for-pr-to-review-column
#          uses: ./
#          if: github.event_name == 'pull_request' && github.event.action == 'opened'
#          with:  
#            myToken: ${{ secrets.GITHUB_TOKEN }}
#            step: 'movePRcard'
#            projectURL: 'https://github.com/nostarch-foundation/grant-actions/projects/1'
#            columnName: 'Review'