# Cribbing from https://github.com/takanabe/github-actions-automate-projects
name: "grant-application-workflow-actions"
on:
    issues:
        types: [opened, labeled]
    
jobs:
    grant-actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: add-project-card-for-issue
              uses: ./
              if: github.event_name == 'issues' && github.event.action == 'opened'
              with:
                myToken: ${{ secrets.GITHUB_TOKEN }}
                step: 'card-for-request'
                projectURL: 'https://github.com/nostarch-foundation/grant-actions/projects/1'
                requestColumn: 'Applications'
            - name: move-request-to-review
              uses: ./
              if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'Review'
              with:
                myToken: ${{ secrets.GITHUB_TOKEN }}
                step: 'request-to-review'
                projectURL: 'https://github.com/nostarch-foundation/grant-actions/projects/1'
                requestColumn: 'Applications'
                reviewColumn: 'To Review'

#        - name: move-issue-card-to-review-column
#          uses: ./
#          if: github.event_name == 'pull_request' && github.event.action == 'opened'
#          with:  
#            myToken: ${{ secrets.GITHUB_TOKEN }}
#            step: 'moveIssuecard'
#            projectURL: 'https://github.com/nostarch-foundation/grant-actions/projects/1'
#            columnName: 'Review'
